### PR TITLE
check that library search path is correct

### PR DESCRIPTION
**Pull request by saraedum**
This does not seem to work for me locally.

### CODE REVIEW

**Comment by saraedum** [comment]
@wlav cppyy does not find libraries installed with conda, i.e., the following does not work:
```
$ conda install gmp

>>> import cppyy
>>>cppyy.load_library('gmp')
```

Is there some environment variable that we can set to point cppyy-cling to our lib directories.

Or should I just patch the `__init__.py` to run the following?
```
import os
cppdef('''
#pragma cling add_include_path("{0}/include")
#pragma cling add_library_path("{0}/lib")
'''.format(os.getenv('CONDA_PREFIX')))
``

Hm…but that does not seem to work actually.

**Comment by wlav** [comment]
Patch should go into cppyy/python/cppyy/_cpython_cppyy.py.

Look for 'add_default_paths' and then if CONDA_PREFIX exists, it needs to be added. The addition of include paths is in `__init__.py`. Probably should move the former there, too, as it's not cpython specific and would be needed for pypy as well.

**Comment by isuruf** [comment]
I suggest what cmake does. For every directory in PATH, look in it or if the directory ends in bin or sbin, look at parent directories lib or lib64 or lib/<architecture>

**Comment by saraedum** [comment]
@isuruf: I ok with that as well. How would that path mangling work on Windows exactly?

**Comment by saraedum** [comment]
And how are these rules about when to use `lib`/`lib64`/`lib/architecture` exactly?

**Comment by saraedum** [comment]
Or should I just add whatever exists? But then I am not sure how this works out with mixed 32/64bit systems.

**Comment by isuruf** [comment]
> Or should I just add whatever exists? But then I am not sure how this works out with mixed 32/64bit systems.

True. Then fixing just for conda makes sense.

**Comment by saraedum** [comment]
@wlav, while I would not recommend to pull this into cppyy, maybe we could have some environment variables for this? `CPPYY_LIBRARY_PATH`/`CPPYY_INCLUDE_PATH` that contains colon separated search paths? It's not really important but if you want me to I could try to upstream something like that.

**Comment by wlav** [comment]
Why not put them in there? I can't think of a reason how this could be problematic. Adding these dynamic paths does not affect what the dynamic linker does (it only affects explicit loads), so is way preferred over changing LD_LIBRARY_PATH to point into conda, for example.

Not that having those two envars wouldn't be useful (although I think the same can be achieved with EXTRA_CLING_ARGS), but conda is common enough just to add them.

**Comment by saraedum** [comment]
@isuruf: unfortunately CONDA_PREFIX does not seem to do the trick. ~During testing of conda-build~ During a build with conda-build this seems to be the build-prefix and not the ~test~host-prefix. It should really be the prefix where cppyy itself lives.

**Comment by saraedum** [comment]
Here's an example:
```
+ pytest --doctest-modules ./../src/gmpxxyy/cppyy_gmpxx.py ./../src/gmpxxyy/__init__.py
============================= test session starts ==============================
platform linux -- Python 3.7.3, pytest-5.2.1, py-1.8.0, pluggy-0.13.0
rootdir: $SRC_DIR/src
Error in <TUnixSystem::FindDynamicLibrary>: gmp[.so | .dll | .dylib | .sl | .dl | .a] does not exist in .:$PREFIX/lib/python3.7/site-packages/cppyy_backend/lib::$BUILD_PREFIX/lib
collected 0 items / 1 errors
```

**Comment by saraedum** [comment]
I guess, I'll just go a few levels up then from where the `cppyy` module is and add that and `../include` if it exists.

**Pull request merged**
